import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://epc.dev.gensomsolar.com/login")
    page.get_by_role("textbox", name="Email Address Password").click()
    page.get_by_role("textbox", name="Email Address Password").fill("ashish.k@sharajman.com")
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).fill("Gensom@1234")
    page.locator("a").click()
    page.get_by_role("button", name="Login").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Engineering Design").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.locator("a").filter(has_text="Sales Handover").click()
    page.get_by_role("link", name=" Project Initialization").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Engineering Design").click()
    page.get_by_role("button").nth(3).click()
    page.locator("a").filter(has_text="Start Design").click()
    page.get_by_role("button", name=" Upload Design Document").click()
    page.locator("p-autocomplete").get_by_role("button").click()
    page.get_by_text("Plant Layout").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator("input[type=\"file\"]").set_input_files("M06 Engineering Design & Layout V1.1.pdf")
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("demo plant layout")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("progressbar", name="%").click()
    page.get_by_role("button", name=" Upload Design Document").click()
    page.locator("p-autocomplete").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_text("Single Line Diagram (SLD)").click()
    page.get_by_text("Click to browse PDF or DOCX (").click()
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("demo sld")
    page.get_by_role("button", name=" Upload").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator("input[type=\"file\"]").set_input_files("GenSOM Solar - Release Note v1.3.1 [09-07-2026].pdf")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("button", name=" Upload Design Document").click()
    page.locator("p-autocomplete").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_role("option", name="Structural Layout").dblclick()
    page.locator("p-autocomplete").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_text("Structural Layout").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator("input[type=\"file\"]").set_input_files("M04_EPC_Project_UC_01_Project Kickoff & Alignment (1).pdf")
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("deo structure")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("button", name=" Upload Design Document").click()
    page.locator("p-autocomplete").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_text("Foundation Design").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator("input[type=\"file\"]").set_input_files("M03_EPC_Finance_UC 1 _ Token Money Receipt & Finance Verification.pdf")
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("demo foundation")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("button", name=" Save For Approval").click()
    page.goto("https://epc.dev.gensomsolar.com/engineering-dash")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)



def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://epc.dev.gensomsolar.com/login")
    page.get_by_role("textbox", name="Email Address Password").click()
    page.get_by_role("textbox", name="Email Address Password").fill("ashish.k@sharajman.com")
    page.get_by_role("textbox", name="Email Address Password").press("Tab")
    page.get_by_role("textbox", name="Password", exact=True).fill("Gensom@1234")
    page.locator("a").click()
    page.get_by_role("button", name="Login").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Engineering Design").click()
    page.locator("tr:nth-child(6) > td:nth-child(10) > p-button > .p-ripple").click()
    page.locator("a").filter(has_text="Submit for Final Approval").click()
    page.get_by_role("row", name="1 M06 Engineering Design &").get_by_placeholder("Add remarks").click()
    page.get_by_role("row", name="1 M06 Engineering Design &").get_by_placeholder("Add remarks").fill("done")
    page.get_by_role("row", name="2 GenSOM Solar - Release Note").get_by_placeholder("Add remarks").click()
    page.get_by_role("row", name="2 GenSOM Solar - Release Note").get_by_placeholder("Add remarks").fill("done")
    page.get_by_role("row", name="M04_EPC_Project_UC_01_Project Kickoff & Alignment (1).pdf Structural Layout").get_by_placeholder("Add remarks").click()
    page.get_by_role("row", name="M04_EPC_Project_UC_01_Project Kickoff & Alignment (1).pdf Structural Layout").get_by_placeholder("Add remarks").fill("done")
    page.get_by_role("row", name="4 M03_EPC_Finance_UC 1 _").get_by_placeholder("Add remarks").click()
    page.get_by_role("row", name="4 M03_EPC_Finance_UC 1 _").get_by_placeholder("Add remarks").fill("done")
    page.get_by_role("textbox", name="Approver Comments ").click()
    page.get_by_role("textbox", name="Approver Comments ").fill("approved")
    page.get_by_role("button", name=" Approve").click()
    page.get_by_role("button", name=" Click to Upload").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.get_by_label("Upload Excel File").set_input_files("category_list (1).xlsx")
    page.get_by_role("button", name=" Save").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("row", name="1 category_list (1).xlsx").get_by_placeholder("Add remarks").click()
    page.get_by_role("row", name="1 category_list (1).xlsx").get_by_placeholder("Add remarks").fill("list added")
    page.get_by_role("button", name=" Approve").click()
    page.get_by_role("button", name=" Submit Report").click()

    
    
    
    page = context.new_page()
    page.goto("https://epc.dev.gensomsolar.com/login")
    page.get_by_role("textbox", name="Email Address Password").click()
    page.get_by_role("textbox", name="Email Address Password").fill("ashish.k@sharajman.com")
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).fill("Gesnom@1234")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="Login").click()
    page.locator("a").click()
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowLeft")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowRight")
    page.get_by_role("textbox", name="Password", exact=True).press("ArrowRight")
    page.get_by_role("textbox", name="Password", exact=True).fill("Gensom@1234")
    page.get_by_role("button", name="Login").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Engineering Design").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("0023")
    page.get_by_role("textbox", name="Search").press("Enter")
    page.get_by_role("button").nth(3).click()
    page.locator("a").filter(has_text="Start Design").click()
    page.get_by_role("button", name=" Cancel").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Search").fill("0032")
    page.get_by_role("textbox", name="Search").press("Enter")
    page.get_by_role("button").nth(3).click()
    page.locator("a").filter(has_text="Submit for Approval").click()
    page.get_by_role("button", name=" Cancel").click()
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
