import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://epc.demo.gensomsolar.com/login")
    page.get_by_role("textbox", name="Email Address Password").click()
    page.get_by_role("textbox", name="Email Address Password").fill("ashish.k@sharajman.com")
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).fill("Gensom@1234")
    page.get_by_role("button", name="Login").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Site Survey").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(4).click()
    page.locator("a").filter(has_text="Submit Survey").click()
    page.get_by_role("region", name="Request Information").get_by_label("Choose Date").click()
    page.get_by_text("8", exact=True).click()
    page.get_by_role("textbox", name="Site Address ").click()
    page.get_by_role("textbox", name="Site Address ").fill("noida, up")
    page.get_by_role("textbox", name="GPS Coordinates (Latitude) ").click()
    page.get_by_role("textbox", name="GPS Coordinates (Latitude) ").fill("12.652398")
    page.get_by_role("textbox", name="GPS Coordinates (Longitude) ").click()
    page.get_by_role("textbox", name="GPS Coordinates (Longitude) ").fill("77.858569")
    page.get_by_role("textbox", name="Land Area (Acres) ").click()
    page.get_by_role("textbox", name="Land Area (Acres) ").fill("150")
    page.get_by_role("region", name="Site Information").get_by_role("combobox").click()
    page.get_by_role("option", name="Full").click()
    page.locator("#pn_id_43").get_by_role("combobox").click()
    page.get_by_text("Rooftop Survey").click()
    page.locator("#pn_id_45").get_by_role("combobox").click()
    page.get_by_role("option", name="High").click()
    page.get_by_role("region", name="Survey Requirements").locator("input[type=\"text\"]").click()
    page.get_by_role("button", name="Next Month").dblclick()
    page.get_by_text("30").nth(1).click()
    page.get_by_role("textbox", name="Survey Guidelines /").click()
    page.get_by_role("textbox", name="Survey Guidelines /").fill("this is demo survey ")
    page.get_by_role("region", name="Survey Agency Assignment").locator("button").click()
    page.get_by_role("option", name="ABC Pvt Ltd").click()
    page.locator(".p-select-label.p-select-label-empty").click()
    page.get_by_text("Ashish Singh").click()
    page.get_by_role("textbox", name="Contact Number ").click()
    page.get_by_role("textbox", name="Contact Number ").fill("9658954785")
    page.get_by_role("button", name=" Upload Document").click()
    page.locator(".w-100 > .p-autocomplete > .p-ripple").click()
    page.get_by_role("dialog", name="Upload Document").locator("input[name=\"undefined\"]").click()
    page.get_by_role("dialog", name="Upload Document").locator("input[name=\"undefined\"]").fill("surve")
    page.get_by_role("option", name="Site Survey Report").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.locator("input[type=\"file\"]").set_input_files("M06 Engineering Design & Layout V1.1.pdf")
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("this is demo file of site survey ")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("textbox", name="Remarks").click()
    page.get_by_role("textbox", name="Remarks").fill("this is demo notes of survey.")
    page.get_by_role("button", name=" Assign & Submit").click()

    # ---------------------
    context.close()
    browser.close()
    
def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://epc.demo.gensomsolar.com/login")
    page.get_by_role("textbox", name="Email Address Password").click()
    page.get_by_role("textbox", name="Email Address Password").fill("ashish.k@sharajman.com")
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).fill("Gensom@1234")
    page.get_by_role("button", name="Login").click()
    page.locator("a").filter(has_text="Project Management").click()
    page.get_by_role("link", name=" Site Survey").click()
    page.locator("tr:nth-child(3) > td:nth-child(15) > p-button > .p-ripple").click()
    page.locator("a").filter(has_text="Submit Report").click()
    page.get_by_role("button", name="Choose Date").click()
    page.get_by_text("14").click()
    page.locator("#roof_type").click()
    page.get_by_role("option", name="RCC").click()
    page.get_by_role("textbox", name="Total Usable Roof Area (sq.ft").click()
    page.get_by_role("textbox", name="Total Usable Roof Area (sq.ft").fill("100")
    page.locator("#roof_orientation").click()
    page.get_by_role("option", name="South", exact=True).click()
    page.locator("#shading_condition").click()
    page.get_by_role("option", name="Partial Shading").click()
    page.get_by_role("textbox", name="Recommended Capacity (kW)").click()
    page.get_by_role("textbox", name="Recommended Capacity (kW)").fill("50")
    page.locator("#phase").click()
    page.get_by_text("Three Phase").click()
    page.locator("#meter_type").click()
    page.get_by_text("Single Phase Meter").click()
    page.locator("#earthing_available").click()
    page.get_by_role("option", name="Yes").click()
    page.get_by_role("button", name=" Upload Document").click()
    page.locator(".p-ripple.p-autocomplete-dropdown").click()
    page.locator("input[name=\"undefined\"]").click()
    page.locator("input[name=\"undefined\"]").fill("surve")
    page.get_by_text("Site Survey Report").click()
    page.get_by_text("Click to browse PDF or DOCX (").click()
    page.locator("input[type=\"file\"]").set_input_files("M06 Engineering Design & Layout V1.1.pdf")
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("Demo survey file of submit report")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("button", name=" Upload Document").click()
    page.locator(".p-ripple.p-autocomplete-dropdown").click()
    page.locator("input[name=\"undefined\"]").fill("surve")
    page.get_by_label("Option List").get_by_text("Site Survey Report").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.get_by_role("textbox", name="Enter description").click()
    page.get_by_role("textbox", name="Enter description").fill("Site survey report")
    page.locator(".p-inputtext.p-component.w-100.ng-untouched.ng-pristine.ng-invalid").click()
    page.locator(".pi.pi-cloud-upload.upload-icon").click()
    page.get_by_text("Click to browse PDF or DOCX (").click()
    page.locator("input[type=\"file\"]").set_input_files("M04_EPC_Project_UC_01_Project Kickoff & Alignment (1) (1).pdf")
    page.get_by_role("button", name=" Upload").click()
    page.get_by_role("button", name=" Submit Report").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)